//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCreator.Models
{
    using System;
    using System.Collections.Generic;
    


    public partial class DIVAAPILOG
    {
        public int Id { get; set; }
        public string RequestMethod { get; set; }
        public string RequestContent { get; set; }
        public System.DateTime RequestTimestamp { get; set; }
        public string ResponseContent { get; set; }
        public System.DateTime ResponseTimestamp { get; set; }

       
    }
}
